# Generated by Django 4.0 on 2022-01-12 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('albumId', models.AutoField(primary_key=True, serialize=False)),
                ('topic', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('shareMode', models.CharField(choices=[('A', 'Public'), ('D', 'Private')], default='D', max_length=1)),
                ('dateCreated', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('dateModified', models.DateTimeField(auto_now=True, verbose_name='date modified')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('postId', models.AutoField(primary_key=True, serialize=False)),
                ('caption', models.CharField(blank=True, max_length=500)),
                ('numberHeart', models.IntegerField(default=0)),
                ('numberComment', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('dateCreated', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('dateModified', models.DateTimeField(auto_now=True, verbose_name='date modified')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserHeart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreated', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('postId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.post')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, max_length=500)),
                ('dateCreated', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('dateModified', models.DateTimeField(auto_now=True, verbose_name='date modified')),
                ('postId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.post')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('U', 'Unsure')], max_length=1)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('crushId', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('imageId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=500)),
                ('path', models.ImageField(upload_to='')),
                ('dateCreated', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('dateModified', models.DateTimeField(auto_now=True, verbose_name='date modified')),
                ('postId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.post')),
            ],
        ),
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.ImageField(upload_to='')),
                ('dateCreated', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('dateModified', models.DateTimeField(auto_now=True, verbose_name='date modified')),
                ('albumId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post.album')),
                ('userId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='AlbumPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreated', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('albumId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.album')),
                ('postId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.post')),
            ],
        ),
    ]
